RAW_FOLDER_PATH = './raw'
OUTPUT_FOLDER_PATH = './output'

STATIC_COLUMNS = {
    'Image': 'Pictures',
    'ResponseTime': 'response_time',
    'Correct': 'correct',
    'ExperimentType': 'experiment_file',
    'ResponseTimeMriTrigger': 'response_time_mritrigger',
    'TimeMriTrigger': 'time_mritrigger',
    'Incon_1': 'time_pic_incon_1',
    'Incon_2': 'time_pic_incon_2',
    'Incon_3': 'time_pic_incon_3',
    'Incon_4': 'time_pic_incon_4',
    'Incon_5': 'time_pic_incon_5',
    'Incon_6': 'time_pic_incon_6',
    'Incon_7': 'time_pic_incon_7',
    'Incon_8': 'time_pic_incon_8',
    'Con_1': 'time_pic_con_1',
    'Con_2': 'time_pic_con_2',
    'Con_3': 'time_pic_con_3',
    'Con_4': 'time_pic_con_4',
    'Con_5': 'time_pic_con_5',
    'Con_6': 'time_pic_con_6',
    'Con_7': 'time_pic_con_7',
    'Con_8': 'time_pic_con_8',
    'InstIncon_1': 'time_incongruent_instructions_1',
    'InstIncon_2': 'time_incongruent_instructions_2',
    'InstIncon_3': 'time_incongruent_instructions_3',
    'InstIncon_4': 'time_incongruent_instructions_4',
    'InstIncon_5': 'time_incongruent_instructions_5',
    'InstIncon_6': 'time_incongruent_instructions_6',
    'InstIncon_7': 'time_incongruent_instructions_7',
    'InstIncon_8': 'time_incongruent_instructions_8',
    'InstCon_1': 'time_congruent_instructions_1',
    'InstCon_2': 'time_congruent_instructions_2',
    'InstCon_3': 'time_congruent_instructions_3',
    'InstCon_4': 'time_congruent_instructions_4',
    'InstCon_5': 'time_congruent_instructions_5',
    'InstCon_6': 'time_congruent_instructions_6',
    'InstCon_7': 'time_congruent_instructions_7',
    'InstCon_8': 'time_congruent_instructions_8',
}
